### ISSUE TITLE
Form Submission

### ISSUE THREAD

**Issue by Abhisheknanda1344463** [niiknow/grapesjs-components-farmer#7]
Hi @noogen  
Could you please tell how could i achieve the form submission with AJAX on a preview page of grapesjs.
Do you have bit of code which you would like to share?
Thanks

**Comment by noogen** [comment]
You want to get the form https://github.com/niiknow/grapesjs-components-farmer/blob/master/src/client.js#L257

Then serialize the data in order to pass the data into ajax https://github.com/niiknow/grapesjs-components-farmer/blob/master/src/client.js#L270

https://github.com/niiknow/grapesjs-components-farmer/blob/master/src/client.js#L312
https://github.com/niiknow/grapesjs-components-farmer/blob/master/src/client.js#L158

**Comment by Abhisheknanda1344463** [comment]
@noogen  Thanks for helping me.
Closing this one.
